// Mock data for sports, leagues, and events
// This will be replaced with real API data later

export const MOCK_SPORTS = [
  {
    _id: "sport_soccer",
    name: "Soccer",
    slug: "soccer",
    icon: "/sports/soccer-ball.png",
    order: 1,
    isActive: true,
    isFeatured: true,
    category: "sports",
    availableMarkets: ["1X2", "Over/Under", "Both Teams to Score", "Correct Score", "Handicap"],
  },
  {
    _id: "sport_basketball",
    name: "Basketball",
    slug: "basketball",
    icon: "/sports/basketball-ball.png",
    order: 2,
    isActive: true,
    isFeatured: true,
    category: "sports",
    availableMarkets: ["Money Line", "Spread", "Total Points", "Quarter Betting"],
  },
  {
    _id: "sport_cricket",
    name: "Cricket",
    slug: "cricket",
    icon: "/sports/cricket-ball.png",
    order: 3,
    isActive: true,
    isFeatured: true,
    category: "sports",
    availableMarkets: ["Match Winner", "Top Batsman", "Top Bowler", "Total Runs"],
  },
  {
    _id: "sport_tennis",
    name: "Tennis",
    slug: "tennis",
    icon: "/sports/tennis-ball.png",
    order: 4,
    isActive: true,
    isFeatured: true,
    category: "sports",
    availableMarkets: ["Match Winner", "Set Betting", "Total Games", "Handicap"],
  },
  {
    _id: "sport_horses",
    name: "Horse Racing",
    slug: "horses",
    icon: "/sports/horse-racing.png",
    order: 5,
    isActive: true,
    isFeatured: true,
    category: "racing",
    availableMarkets: ["Win", "Place", "Each Way", "Forecast", "Tricast"],
  },
  {
    _id: "sport_esports",
    name: "Esports",
    slug: "esports",
    icon: "/sports/gamepad-esports.png",
    order: 6,
    isActive: true,
    isFeatured: true,
    category: "esports",
    availableMarkets: ["Match Winner", "Map Winner", "Handicap", "Total Maps"],
  },
  {
    _id: "sport_boxing",
    name: "Boxing",
    slug: "boxing",
    icon: "/sports/boxing-gloves.png",
    order: 7,
    isActive: true,
    isFeatured: true,
    category: "sports",
    availableMarkets: ["Fight Winner", "Method of Victory", "Round Betting"],
  },
  {
    _id: "sport_golf",
    name: "Golf",
    slug: "golf",
    icon: "/sports/golf-ball.png",
    order: 8,
    isActive: true,
    isFeatured: true,
    category: "sports",
    availableMarkets: ["Tournament Winner", "Top 5 Finish", "Head to Head"],
  },
  {
    _id: "sport_formula1",
    name: "Formula 1",
    slug: "formula1",
    icon: "/sports/formula1-car.png",
    order: 9,
    isActive: true,
    isFeatured: true,
    category: "racing",
    availableMarkets: ["Race Winner", "Podium Finish", "Fastest Lap"],
  },
  {
    _id: "sport_virtual",
    name: "Virtual Sports",
    slug: "virtual",
    icon: "/sports/virtual-sports.png",
    order: 10,
    isActive: true,
    isFeatured: true,
    category: "virtual",
    availableMarkets: ["Match Winner", "Correct Score", "Over/Under"],
  },
]

export const MOCK_LEAGUES = [
  // Soccer Leagues
  {
    _id: "league_epl",
    name: "English Premier League",
    slug: "english-premier-league",
    sportId: "sport_soccer",
    country: "England",
    countryCode: "GB",
    logo: "/leagues/premier-league.png",
    order: 1,
    isActive: true,
    isFeatured: true,
  },
  {
    _id: "league_laliga",
    name: "La Liga",
    slug: "la-liga",
    sportId: "sport_soccer",
    country: "Spain",
    countryCode: "ES",
    logo: "/leagues/la-liga.png",
    order: 2,
    isActive: true,
    isFeatured: true,
  },
  {
    _id: "league_bundesliga",
    name: "Bundesliga",
    slug: "bundesliga",
    sportId: "sport_soccer",
    country: "Germany",
    countryCode: "DE",
    logo: "/leagues/bundesliga.png",
    order: 3,
    isActive: true,
    isFeatured: true,
  },
  {
    _id: "league_seriea",
    name: "Serie A",
    slug: "serie-a",
    sportId: "sport_soccer",
    country: "Italy",
    countryCode: "IT",
    logo: "/leagues/serie-a.png",
    order: 4,
    isActive: true,
    isFeatured: true,
  },
  {
    _id: "league_ligue1",
    name: "Ligue 1",
    slug: "ligue-1",
    sportId: "sport_soccer",
    country: "France",
    countryCode: "FR",
    logo: "/leagues/ligue-1.png",
    order: 5,
    isActive: true,
    isFeatured: false,
  },
  {
    _id: "league_ucl",
    name: "UEFA Champions League",
    slug: "champions-league",
    sportId: "sport_soccer",
    country: "Europe",
    countryCode: "EU",
    logo: "/leagues/champions-league.png",
    order: 0,
    isActive: true,
    isFeatured: true,
  },
  // Basketball Leagues
  {
    _id: "league_nba",
    name: "NBA",
    slug: "nba",
    sportId: "sport_basketball",
    country: "USA",
    countryCode: "US",
    logo: "/leagues/nba.png",
    order: 1,
    isActive: true,
    isFeatured: true,
  },
  {
    _id: "league_euroleague",
    name: "EuroLeague",
    slug: "euroleague",
    sportId: "sport_basketball",
    country: "Europe",
    countryCode: "EU",
    logo: "/leagues/euroleague.png",
    order: 2,
    isActive: true,
    isFeatured: false,
  },
  // Cricket Leagues
  {
    _id: "league_ipl",
    name: "Indian Premier League",
    slug: "ipl",
    sportId: "sport_cricket",
    country: "India",
    countryCode: "IN",
    logo: "/leagues/ipl.png",
    order: 1,
    isActive: true,
    isFeatured: true,
  },
  // Tennis
  {
    _id: "league_atp",
    name: "ATP Tour",
    slug: "atp-tour",
    sportId: "sport_tennis",
    country: "International",
    countryCode: "INT",
    logo: "/leagues/atp.png",
    order: 1,
    isActive: true,
    isFeatured: true,
  },
  // Esports
  {
    _id: "league_lol",
    name: "League of Legends World Championship",
    slug: "lol-worlds",
    sportId: "sport_esports",
    country: "International",
    countryCode: "INT",
    logo: "/leagues/lol.png",
    order: 1,
    isActive: true,
    isFeatured: true,
  },
  {
    _id: "league_csgo",
    name: "CS:GO Major",
    slug: "csgo-major",
    sportId: "sport_esports",
    country: "International",
    countryCode: "INT",
    logo: "/leagues/csgo.png",
    order: 2,
    isActive: true,
    isFeatured: true,
  },
]

// Helper to generate dynamic events
const generateFutureDate = (hoursFromNow) => {
  const date = new Date()
  date.setHours(date.getHours() + hoursFromNow)
  return date.toISOString()
}

export const MOCK_EVENTS = [
  // Premier League matches
  {
    _id: "event_1",
    name: "Manchester United vs Liverpool",
    sportId: "sport_soccer",
    leagueId: "league_epl",
    homeTeam: { name: "Manchester United", logo: "/teams/man-utd.png", score: null },
    awayTeam: { name: "Liverpool", logo: "/teams/liverpool.png", score: null },
    startTime: generateFutureDate(2),
    status: "scheduled",
    isFeatured: true,
    isBettingOpen: true,
  },
  {
    _id: "event_2",
    name: "Arsenal vs Chelsea",
    sportId: "sport_soccer",
    leagueId: "league_epl",
    homeTeam: { name: "Arsenal", logo: "/teams/arsenal.png", score: 1 },
    awayTeam: { name: "Chelsea", logo: "/teams/chelsea.png", score: 1 },
    startTime: generateFutureDate(-1),
    status: "live",
    liveInfo: { minute: 67, period: "2nd Half", isBreak: false },
    isFeatured: true,
    isBettingOpen: true,
  },
  {
    _id: "event_3",
    name: "Manchester City vs Tottenham",
    sportId: "sport_soccer",
    leagueId: "league_epl",
    homeTeam: { name: "Manchester City", logo: "/teams/man-city.png", score: null },
    awayTeam: { name: "Tottenham", logo: "/teams/spurs.png", score: null },
    startTime: generateFutureDate(26),
    status: "scheduled",
    isFeatured: true,
    isBettingOpen: true,
  },
  // La Liga matches
  {
    _id: "event_4",
    name: "Real Madrid vs Barcelona",
    sportId: "sport_soccer",
    leagueId: "league_laliga",
    homeTeam: { name: "Real Madrid", logo: "/teams/real-madrid.png", score: null },
    awayTeam: { name: "Barcelona", logo: "/teams/barcelona.png", score: null },
    startTime: generateFutureDate(48),
    status: "scheduled",
    isFeatured: true,
    isBettingOpen: true,
  },
  {
    _id: "event_5",
    name: "Atletico Madrid vs Sevilla",
    sportId: "sport_soccer",
    leagueId: "league_laliga",
    homeTeam: { name: "Atletico Madrid", logo: "/teams/atletico.png", score: 2 },
    awayTeam: { name: "Sevilla", logo: "/teams/sevilla.png", score: 0 },
    startTime: generateFutureDate(-0.5),
    status: "live",
    liveInfo: { minute: 34, period: "1st Half", isBreak: false },
    isFeatured: false,
    isBettingOpen: true,
  },
  // Champions League
  {
    _id: "event_6",
    name: "Bayern Munich vs PSG",
    sportId: "sport_soccer",
    leagueId: "league_ucl",
    homeTeam: { name: "Bayern Munich", logo: "/teams/bayern.png", score: null },
    awayTeam: { name: "Paris Saint-Germain", logo: "/teams/psg.png", score: null },
    startTime: generateFutureDate(72),
    status: "scheduled",
    isFeatured: true,
    isBettingOpen: true,
  },
  // NBA matches
  {
    _id: "event_7",
    name: "Lakers vs Celtics",
    sportId: "sport_basketball",
    leagueId: "league_nba",
    homeTeam: { name: "LA Lakers", logo: "/teams/lakers.png", score: 87 },
    awayTeam: { name: "Boston Celtics", logo: "/teams/celtics.png", score: 92 },
    startTime: generateFutureDate(-0.3),
    status: "live",
    liveInfo: { minute: 0, period: "Q3", isBreak: false },
    isFeatured: true,
    isBettingOpen: true,
  },
  {
    _id: "event_8",
    name: "Warriors vs Bucks",
    sportId: "sport_basketball",
    leagueId: "league_nba",
    homeTeam: { name: "Golden State Warriors", logo: "/teams/warriors.png", score: null },
    awayTeam: { name: "Milwaukee Bucks", logo: "/teams/bucks.png", score: null },
    startTime: generateFutureDate(5),
    status: "scheduled",
    isFeatured: true,
    isBettingOpen: true,
  },
  // Cricket
  {
    _id: "event_9",
    name: "Mumbai Indians vs Chennai Super Kings",
    sportId: "sport_cricket",
    leagueId: "league_ipl",
    homeTeam: { name: "Mumbai Indians", logo: "/teams/mi.png", score: null },
    awayTeam: { name: "Chennai Super Kings", logo: "/teams/csk.png", score: null },
    startTime: generateFutureDate(24),
    status: "scheduled",
    isFeatured: true,
    isBettingOpen: true,
  },
  // Tennis
  {
    _id: "event_10",
    name: "Djokovic vs Alcaraz",
    sportId: "sport_tennis",
    leagueId: "league_atp",
    homeTeam: { name: "Novak Djokovic", logo: "/players/djokovic.png", score: null },
    awayTeam: { name: "Carlos Alcaraz", logo: "/players/alcaraz.png", score: null },
    startTime: generateFutureDate(6),
    status: "scheduled",
    isFeatured: true,
    isBettingOpen: true,
  },
  // Esports
  {
    _id: "event_11",
    name: "T1 vs Gen.G",
    sportId: "sport_esports",
    leagueId: "league_lol",
    homeTeam: { name: "T1", logo: "/teams/t1.png", score: 1 },
    awayTeam: { name: "Gen.G", logo: "/teams/geng.png", score: 2 },
    startTime: generateFutureDate(-0.2),
    status: "live",
    liveInfo: { minute: 0, period: "Game 4", isBreak: false },
    isFeatured: true,
    isBettingOpen: true,
  },
]

// Generate markets for each event
export const generateMarketsForEvent = (event) => {
  const markets = []

  // 1X2 / Match Winner (main market)
  markets.push({
    _id: `market_${event._id}_1x2`,
    eventId: event._id,
    type: "1X2",
    name: "Match Result",
    category: "main",
    isMain: true,
    order: 1,
    status: "open",
    selections: [
      {
        name: event.homeTeam.name,
        odds: Number.parseFloat((1.5 + Math.random() * 1.5).toFixed(2)),
        status: "open",
        result: "pending",
      },
      {
        name: "Draw",
        odds: Number.parseFloat((2.8 + Math.random() * 1).toFixed(2)),
        status: "open",
        result: "pending",
      },
      {
        name: event.awayTeam.name,
        odds: Number.parseFloat((2 + Math.random() * 2).toFixed(2)),
        status: "open",
        result: "pending",
      },
    ],
  })

  // Over/Under 2.5
  markets.push({
    _id: `market_${event._id}_ou25`,
    eventId: event._id,
    type: "Over/Under",
    name: "Total Goals Over/Under 2.5",
    category: "goals",
    isMain: false,
    order: 2,
    status: "open",
    selections: [
      {
        name: "Over 2.5",
        odds: Number.parseFloat((1.7 + Math.random() * 0.5).toFixed(2)),
        status: "open",
        result: "pending",
        line: 2.5,
      },
      {
        name: "Under 2.5",
        odds: Number.parseFloat((1.9 + Math.random() * 0.5).toFixed(2)),
        status: "open",
        result: "pending",
        line: 2.5,
      },
    ],
  })

  // Both Teams to Score
  markets.push({
    _id: `market_${event._id}_btts`,
    eventId: event._id,
    type: "BTTS",
    name: "Both Teams to Score",
    category: "goals",
    isMain: false,
    order: 3,
    status: "open",
    selections: [
      {
        name: "Yes",
        odds: Number.parseFloat((1.6 + Math.random() * 0.4).toFixed(2)),
        status: "open",
        result: "pending",
      },
      { name: "No", odds: Number.parseFloat((2 + Math.random() * 0.5).toFixed(2)), status: "open", result: "pending" },
    ],
  })

  // Double Chance
  markets.push({
    _id: `market_${event._id}_dc`,
    eventId: event._id,
    type: "Double Chance",
    name: "Double Chance",
    category: "main",
    isMain: false,
    order: 4,
    status: "open",
    selections: [
      {
        name: `${event.homeTeam.name} or Draw`,
        odds: Number.parseFloat((1.2 + Math.random() * 0.3).toFixed(2)),
        status: "open",
        result: "pending",
      },
      {
        name: `${event.homeTeam.name} or ${event.awayTeam.name}`,
        odds: Number.parseFloat((1.1 + Math.random() * 0.2).toFixed(2)),
        status: "open",
        result: "pending",
      },
      {
        name: `Draw or ${event.awayTeam.name}`,
        odds: Number.parseFloat((1.3 + Math.random() * 0.4).toFixed(2)),
        status: "open",
        result: "pending",
      },
    ],
  })

  // Correct Score (top 6 options)
  markets.push({
    _id: `market_${event._id}_cs`,
    eventId: event._id,
    type: "Correct Score",
    name: "Correct Score",
    category: "goals",
    isMain: false,
    order: 5,
    status: "open",
    selections: [
      { name: "1-0", odds: Number.parseFloat((6 + Math.random() * 3).toFixed(2)), status: "open", result: "pending" },
      { name: "2-0", odds: Number.parseFloat((8 + Math.random() * 4).toFixed(2)), status: "open", result: "pending" },
      { name: "2-1", odds: Number.parseFloat((7 + Math.random() * 3).toFixed(2)), status: "open", result: "pending" },
      { name: "1-1", odds: Number.parseFloat((5 + Math.random() * 2).toFixed(2)), status: "open", result: "pending" },
      { name: "0-1", odds: Number.parseFloat((7 + Math.random() * 4).toFixed(2)), status: "open", result: "pending" },
      { name: "0-2", odds: Number.parseFloat((10 + Math.random() * 5).toFixed(2)), status: "open", result: "pending" },
    ],
  })

  return markets
}

// Generate all markets
export const MOCK_MARKETS = MOCK_EVENTS.flatMap((event) => generateMarketsForEvent(event))
